spring.application.name=faceRecon
spring.datasource.url=jdbc:postgresql://localhost:5432/faceRecon
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}
server.servlet.contextPath=/api

spring.http.client.connect-timeout=30s
spring.http.client.read-timeout=5s

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

application.file.watch.daemon=true
application.file.watch.pollInterval=5
application.file.watch.quietPeriod=1
application.file.watch.directory=C:\\workspace\\files\\customer

imagerecognition.base-url=${DEEPFACE_API:http://127.0.0.1:5005}
app.upload.dir=${user.dir}/uploads
